name: qrpass
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  mobile_scanner: ^6.0.10
  pretty_qr_code: ^3.4.0
  permission_handler: ^11.3.0
  qr_flutter: ^4.1.0
  web_socket_channel: ^3.0.3
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  http: ^1.3.0
  shared_preferences: ^2.5.3
  http_parser: ^4.1.2
  provider: ^6.0.0
  mime: ^2.0.0
  connectivity_plus: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/image/   # <-- folder name is 'asset', not 'assets'

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "asset/image/symbole.png"  # <-- update path
  background_color: "#FFFFFF"
  min_sdk_android: 21

flutter_native_splash:
  android: true
  ios: true
  image: "asset/image/symbole.png"  # <-- update path
  color: "#FFFFFF"
